name: NPM publish 🚀

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Node.js v22.*'
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install dependencies (npm install) 📦...'
        run: npm install

      - name: 'Run build (npm run build) 🔧...'
        run: npm run build

      - name: 'Publish package'
        uses: JS-DevTools/npm-publish@v3
        with:
          registry: 'https://registry.npmjs.org/'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
